Repository Cylink-KSM-Cyber/backend-cylink, pull requests merged in 2025-07, with the labels that each got.

#119 chore: remove legacy migration system files and enhance Knex migration documentation with comprehensive best practices guide
  README.md
  jest.config.js
  package.json
  src/config/knex.ts
  src/database/migrations.ts
  src/database/schema.ts
  src/database/scripts/migrations/20250712124317_fix_short_code_length.ts
  src/database/scripts/migrations/20250712131315_add_unique_constraint_url_conversion_goals.ts
  src/docs/migration-best-practices.md
Labels: documentation, enhancement

#121 fix: sentry auth and logger utils
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  src/index.ts
  src/utils/logger.ts
Labels: enhancement

#127 feat: user-registration-email-verification: Modular validation, robust tests, unified email templates, error codes, and config improvements
  .env.example
  package.json
  src/__tests__/controllers/registrationController.test.ts
  src/__tests__/mails/registerMail.test.ts
  src/__tests__/services/verificationService.test.ts
  src/__tests__/validators/registrationValidator.test.ts
  src/config/mailer.ts
  src/controllers/registrationController.ts
  src/controllers/verificationController.ts
  src/interfaces/RegistrationRequest.ts
  src/mails/register.ts
  src/models/userModel.ts
  src/routes/authRoutes.ts
  src/services/registrationService.ts
  src/services/verificationService.ts
  src/validators/registrationValidator.ts
Labels: bug, enhancement
