Repository Cylink-KSM-Cyber/backend-cylink, pull requests merged in 2025-05, with the labels that each got.

#44 fix: force recreate image after commit
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  package-lock.json
Labels: enhancement

#45 fix: force to not using cache on webserver build
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#46 fix: fallback to webserver manual build
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  docker-compose.staging.yml
  docker-compose.yml
  docker/webserver/Dockerfile
  docker/webserver/entrypoint.sh
  docker/webserver/nginx.conf
Labels: enhancement

#47 Staging
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  docker-compose.staging.yml
  docker-compose.yml
  docker/webserver/Dockerfile
  docker/webserver/entrypoint.sh
  docker/webserver/nginx.conf
  package-lock.json
Labels: enhancement

#48 fix: issue on env override
  docker-compose.yml
Labels: enhancement

#49 fix: docker-compose environment separation
  .github/workflows/deploy.prod.yml
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker-compose.yml
Labels: enhancement

#50 fix: duplicating env value into docker compose script
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  docker-compose.yml
Labels: enhancement

#51 hotfix: minor fix at api variable name
  docker-compose.yml
Labels: enhancement

#52 fix: omitting docker volumes
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker/api/Dockerfile
Labels: enhancement

#53 hotfix: include database volume
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker-compose.yml
Labels: enhancement

#54 Staging
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker-compose.yml
  docker/api/Dockerfile
Labels: enhancement

#56 Staging
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#57 fix: overlapping network stack
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker-compose.yml
Labels: enhancement

#58 Staging
  docker-compose.prod.yml
  docker-compose.staging.yml
  docker-compose.yml
Labels: enhancement

#61 fix: get rid of untracked changes on the deployment server
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#64 chore: tidy up variable names
  docker-compose.prod.yml
  docker-compose.yml
Labels: enhancement

#65 chore: tidy up variable names
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#67 Staging
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  docker-compose.prod.yml
  docker-compose.yml
  logs/combined.log
  src/controllers/qrCodeController.ts
  src/controllers/urlController.ts
  src/interfaces/URL.ts
  src/models/qrCodeModel.ts
  src/models/urlModel.ts
  src/services/qrCodeService.ts
  src/services/urlService.ts
  src/validators/qrCodeValidator.ts
  src/validators/urlValidator.ts
Labels: enhancement

#70 hotfix: remove environment prefix on .env file
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#71 fix: only clear build cache instead of entire cache
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#73 chore: revert back to system prune
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#74 Dev
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#78 hotfix: could not pass utm campaigns on the original URL
  docker/webserver/nginx.conf
Labels: enhancement

#79 hotfix: includes origin header on the containerized webserver
  docker/webserver/nginx.conf
Labels: enhancement

#81 hotfix: swapping request_uri with uri
  docker/webserver/nginx.conf
Labels: enhancement

#82 hotfix: using static dns resolver
  docker/webserver/nginx.conf
Labels: enhancement

#83 refactor: Implement SOLID principles in QR code controller by separating concerns
  src/controllers/qr-code/createQrCodeController.ts
  src/controllers/qr-code/deleteQrCodeByIdController.ts
  src/controllers/qr-code/downloadQrCodeControllers.ts
  src/controllers/qr-code/getQrCodeByIdController.ts
  src/controllers/qr-code/getQrCodeByShortCodeController.ts
  src/controllers/qr-code/getQrCodeByUrlIdController.ts
  src/controllers/qr-code/getQrCodeColorOptionsController.ts
  src/controllers/qr-code/getQrCodesByUserController.ts
  src/controllers/qr-code/index.ts
  src/controllers/qr-code/updateQrCodeController.ts
  src/controllers/qrCodeController.ts
Labels: bug, documentation, enhancement

#92 hotfix: empty swagger documentation
  docker-compose.yml
Labels: enhancement

#89 feat: implement automatic URL expiration system with real-time status updates and background job processing
  src/__tests__/jobs/urlExpirationJob.test.ts
  src/__tests__/middlewares/urlExpirationMiddleware.test.ts
  src/collections/userCollection.ts
  src/controllers/jobController.ts
  src/controllers/userProfileController.ts
  src/database/indexes.ts
  src/database/migrations/add_auto_expired_at_column.sql
  src/database/migrations/add_user_timezone_column.sql
  src/database/schema.ts
  src/index.ts
  src/jobs/jobScheduler.ts
  src/jobs/urlExpirationJob.ts
  src/middlewares/urlExpirationMiddleware.ts
  src/models/userModel.ts
  src/routes/index.ts
  src/routes/jobRoutes.ts
  src/routes/publicUrlRoutes.ts
  src/routes/urlRoutes.ts
  src/routes/userProfileRoutes.ts
  src/utils/cache.ts
Labels: documentation, enhancement

#91 hotfix: missing utm parameters on redirect
  .gitignore
  src/services/publicUrlService.ts
Labels: enhancement

#93 feat: integrate knexjs for future use
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
  package-lock.json
  package.json
  src/config/knex.ts
  src/database/scripts/migrations/001_users.ts
  src/database/scripts/migrations/002_urls.ts
  src/database/scripts/migrations/003_clicks.ts
  src/database/scripts/migrations/004_impressions.ts
  src/database/scripts/migrations/005_qr_codes.ts
  src/database/scripts/migrations/006_conversion_goals.ts
  src/database/scripts/migrations/007_url_conversion_goals.ts
  src/database/scripts/migrations/008_conversions.ts
Labels: enhancement

#99 hotfix: direct database url for database migration workflow
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#100 hotfix: removed newline for database url during migration
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#104 feat: implement secure password reset endpoint with email confirmation and comprehensive validation
  src/config/mailer.ts
  src/controllers/passwordResetController.ts
  src/mails/password-change-confirmation.ts
  src/middlewares/passwordResetRateLimit.ts
  src/routes/authRoutes.ts
  src/routes/index.ts
  src/utils/passwordValidator.ts
  src/validators/passwordResetValidator.ts
Labels: documentation, enhancement

#101 feat: encoded utm content and url click recorder placeholder
  src/controllers/urlController.ts
  src/controllers/urls/getPublicUrlDetails.ts
  src/controllers/urls/index.ts
  src/controllers/urls/recordUrlClick.ts
  src/interfaces/ClickInfo.ts
  src/routes/publicUrlRoutes.ts
  src/routes/urlRoutes.ts
  src/services/publicUrlService.ts
Labels: enhancement

#105 fix: implement click tracking data recording for public URL endpoint analytics database
  src/controllers/urls/getPublicUrlDetails.ts
Labels: bug
